chess:
  ai-properties:
    type: min-max
    search-depth: 4
  player1: human
  player2: human
system:
  windowing-system: sdl
renderer:
  renderer-backend: metal
  opengl-settings:
    opengl-render-mode: direct
