chess:
  ai-properties:
    type: alpha-beta
    search-depth: 3
    timeout-ms: 10000
  llm-properties:
    provider: gemini
  player1: llm
  player2: human
system:
  secrets-folder: private/apiKeys/
  windowing-system: sdl
  session:
    type: host
    host:
      port: 32000
    join:
      ip: 192.168.1.1
      port: 32000
renderer:
  renderer-backend: metal
  opengl-settings:
    render-mode: classic
