chess:
  ai-properties:
    type: min-max
    search-depth: 3
  player1: human
  player2: ai
system:
  windowing-system: sdl
renderer:
  renderer-backend: opengl
  opengl-settings:
    opengl-render-mode: instance
