chess:
  ai-properties:
    type: alpha-beta
    search-depth: 3
    timeout-ms: 10000
  player1: human
  player2: ai
system:
  windowing-system: sdl
renderer:
  renderer-backend: vulkan
  opengl-settings:
    render-mode: instance
