#pragma once

#define VERSION_MAJOR "0"
#define VERSION_MINOR "1"
#define VERSION_UPDATE "0"
#define VERSION_PATCH ""
#define BUILD_VERSION VERSION_MAJOR "." VERSION_MINOR "." VERSION_UPDATE "-" VERSION_PATCH