name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Setup Script
        run: ${{github.workspace}}/scripts/setup.sh
        
      - name: Downloading SDL
        run: ${{github.workspace}}/scripts/download_sdl.sh
        
      - name: Build
        run: ${{github.workspace}}/scripts/build.sh
          
