name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Setup Script
        run: ${{github.workspace}}/scripts/macos/setup.sh
        
      - name: Downloading SDL
        run: ${{github.workspace}}/scripts/macos/download_sdl.sh
        
      - name: Build
        run: ${{github.workspace}}/scripts/macos/build.sh

      - name: Create Artifact
        run: |
          mkdir release
          cp out release/chess.app
          cp -r resources release/resources
      
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: macos-release
          path: release
          
