#include "Chess/Player.h"
#include "Chess/Players/AIPlayer.h"
#include "Chess/Players/AIs/AlphaBetaAIPlayer.h"
#include "Chess/Players/AIs/MinMaxAIPlayer.h"
#include "Chess/Players/HumanPlayer.h"
#include "Chess/Players/RandomPlayer.h"
